network.host: ${ELK_ELASTIC_HOST}
cluster.name: "tm-elastic-cluster"
discovery.type: single-node
cluster.routing.allocation.disk.threshold_enabled: false

xpack.license.self_generated.type: trial
xpack.security.enabled: true