version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    ports:
      - "80:80"
      - "45981:45981"
    depends_on:
      - elasticsearch
    networks:
      tm:

  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELK_VERSION}
    env_file: .env.prod
    volumes:
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELK_ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${ELK_LOGSTASH_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${ELK_KIBANA_PASSWORD:-}
    networks:
      tm:
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch:/usr/share/elasticsearch/data:z
    restart: always
    env_file: .env.prod
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELK_ELASTIC_PASSWORD:-}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      tm:

  kibana:
    image: kibana:${ELK_VERSION}
    env_file: .env.prod
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${ELK_KIBANA_PASSWORD:-}
    restart: always
    networks:
      tm:
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:${ELK_VERSION}
    env_file: .env.prod
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    restart: always
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${ELK_LOGSTASH_PASSWORD:-}
    networks:
      - tm
    depends_on:
      - elasticsearch

networks:
  tm:
    driver: bridge

volumes:
  setup:
  elasticsearch: