from typing import Final

MARKET_PING_INTERVAL: Final[float] = 170
MARKET_TEST_INTERVAL: Final[float] = 35
MARKET_SET_STEAM_API_INTERVAL: Final[float] = 5
MARKET_UPDATE_INVENTORY_INTERVAL: Final[float] = 60
MARKET_GET_INVENTORY_INTERVAL: Final[float] = 5
MARKET_COLLECTING_PRICES_INTERVAL: Final[float] = 3
