# Generated by Django 4.1 on 2022-09-22 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=99, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('steam_id', models.PositiveBigIntegerField(unique=True)),
                ('steam_api', models.CharField(max_length=99, unique=True)),
                ('shared_secret', models.CharField(max_length=99)),
                ('identity_secret', models.CharField(max_length=99)),
                ('market_api_key', models.CharField(max_length=99, unique=True)),
                ('google_drive_id', models.CharField(max_length=99, unique=True)),
                ('proxy', models.CharField(max_length=99)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('market_hash_name', models.CharField(max_length=120)),
                ('market_ru_name', models.CharField(max_length=120)),
                ('google_price_usd', models.FloatField()),
                ('google_drive_time', models.DateTimeField()),
                ('steam_price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('steam_time', models.DateTimeField()),
                ('status', models.BigIntegerField(choices=[(65536, 'New'), (131072, 'NotAtSteamInv'), (262144, 'Check')], default=262144)),
                ('place', models.IntegerField(choices=[(1, 'Google885'), (2, 'Google886'), (16, 'Google888'), (5, 'Casino'), (8, 'Unknown')], default=8)),
                ('hold', models.DateTimeField()),
                ('hold_status', models.BigIntegerField(choices=[(67108864, 'Undefined'), (33554432, 'Hold'), (16777216, 'NotAtHold')], default=67108864)),
                ('asset_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('trade_id', models.CharField(blank=True, max_length=30)),
                ('drive_discount', models.CharField(max_length=30)),
                ('drive_discount_percent', models.CharField(max_length=30)),
                ('correct_name', models.IntegerField(choices=[(256, 'Yes'), (512, 'No'), (1024, 'Wait')], default=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.account')),
            ],
        ),
    ]
