# Generated by Django 4.1 on 2022-09-29 15:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='item',
            name='min_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BigIntegerField(choices=[(65536, 'New'), (131072, 'NotAtSteamInv'), (262144, 'Check'), (51, 'Wait')], default=262144),
        ),
    ]
