# Generated by Django 4.1 on 2022-10-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_item_market_count_item_market_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='market_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
